name: Ryan Spoon
favicon: null
layout_spectrum: 0.22089
typography_spectrum: 0.5737
title: "@RyanSpoon's Grid: What I'm Reading"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bdce72'
    - '#2eaab6'
    - '#000237'
    - '#a31c6c'
    - '#ff8b99'
  brandStrength: 0.5
  lightness: 0.4784660995937884
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
