name: Ryan Spoon
favicon: null
layout_spectrum: 0.57096
typography_spectrum: 0.5737
title: "@RyanSpoon's Grid: What I'm Reading"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9efeb'
    - '#c3c9bf'
    - '#08070c'
    - '#5a585b'
    - '#a76f4e'
  brandStrength: 0.1875
  lightness: 0.4784660995937884
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
