name: Ryan Spoon
favicon: null
layout_spectrum: 0.57096
typography_spectrum: 0.5737
title: "@RyanSpoon's Grid: What I'm Reading"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01ffff'
    - '#ffffff'
    - '#ff00fe'
    - '#000014'
    - '#ff6200'
  brandStrength: 0.0625
  lightness: 0.4784660995937884
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
